### ISSUE TITLE
Отсутствует загрузка файлов в определенном порядке

### ISSUE THREAD

**Issue by deadelf79** [godsent/rpg-maker-side-script-loader#1]
Так как я даже и не подумаю переименовывать файлы для задания порядка их загрузки, решил задачу таким образом:

```
class SideScriptsLoader
    def load_entries
        dir_entries = Dir.entries(dirname).delete_if{|entry|entry=~/^\./}
    if dir_entries.include?("load.cfg")
        load = load_config
        load.each{|entry|
            entry.gsub!(/[\n]$/){""}
            require filename(entry) if entry =~ /\.rb\Z/
            dir_entries-=["#{entry}.rb"]
        }
    end
    dir_entries.each do |entry|
        require filename(entry) if entry =~ /\.rb\Z/
    end
    end

    def load_config
        open(config,"r").readlines.delete_if{|line|line=~/^[\s]?#/}
    end

    def config
        filename("load.cfg")
    end
end
```

Содержимое файла load.cfg, который помещается в папку, откуда мы грузим код:

```
# Здесь указан порядок загрузки скриптов.
# Не указанные здесь скрипты будут занесены в алфавитном порядке после загрузки указанных
some_script
another_sctipt
```

Прошу добавить это

**Comment by godsent** [comment]
Привет Эльф, отличная фича! 
Есть пара замечаний по коду и оформлению, и здесь их не удобно писать совсем. Может ты сделаешь merge request? Просто форкни проект, сделай новую git ветку от мастера, внеси свои изменения, запуш обратно в форкнутый проект и гит сам предложит тебе сделать pull request.

**Comment by deadelf79** [comment]
Сделал по твоей инструкции ^_^
Заодно обновил readme
